apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uvicorn"]
          args: ["chatbot.src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          env:
            - name: LLM_API_KEY
              value: {{ .Values.config.llm.apiKey | quote }}
            - name: LLM_BASE_URL
              value: {{ .Values.config.llm.baseUrl | quote }} 