apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui
spec:
  replicas: {{ .Values.replicaCount.ui }}
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python"]
          args: ["-m", "chatbot.src.main"]
          ports:
            - containerPort: 7860
          env:
            - name: API_URL
              value: {{ .Values.config.ui.apiUrl }}