apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'chatbot-api'
        static_configs:
          - targets: ['chatbot-api:8000']
        metrics_path: /metrics 