apiVersion: v1
kind: Service
metadata:
  name: chatbot-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.apiPort | int }}
      targetPort: {{ .Values.service.apiPort | int }}
  selector:
    app: chatbot-api
