apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.uiPort | int}}
      targetPort: {{ .Values.service.uiPort | int}}
  selector:
    app: chatbot-ui
