apiVersion: v1
kind: Service
metadata:
  name: chatbot-prometheus
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.prometheus.port | int}}
      targetPort: {{ .Values.config.prometheus.port | int}}
  selector:
    app: chatbot-prometheus 