apiVersion: v1
kind: Service
metadata:
  name: chatbot-grafana
spec:
  type: ClusterIP
  ports:
    - port:  {{ .Values.grafana.port | int}}
      targetPort:  {{ .Values.grafana.port | int}}
  selector:
    app: chatbot-grafana 