kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: spanish-tutor

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8000
        protocol: TCP
      - containerPort: 30001
        hostPort: 7860
        protocol: TCP
      - containerPort: 30002
        hostPort: 9090
        protocol: TCP
      - containerPort: 30003
        hostPort: 3000
        protocol: TCP

  - role: worker
  - role: worker

# Enable feature gates
featureGates:
  PodSecurity: true

# Configure kubeadm
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true" 