apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanish-tutor-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spanish-tutor-prometheus
  template:
    metadata:
      labels:
        app: spanish-tutor-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=200h'
            - '--web.enable-lifecycle'
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config 