apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: {{ .Values.grafana.port }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards-usage-performance
              mountPath: /etc/grafana/dashboards/usage-performance
            - name: grafana-dashboards-reliability
              mountPath: /etc/grafana/dashboards/reliability
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-ds
        - name: grafana-dashboards-provisioning
          configMap:
            name: grafana-dashboards-provisioning
        - name: grafana-dashboards-usage-performance
          configMap:
            name: grafana-dashboard-usage-performance
        - name: grafana-dashboards-reliability
          configMap:
            name: grafana-dashboard-reliability
