apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanish-tutor-ui
spec:
  replicas: {{ .Values.replicaCount.ui }}
  selector:
    matchLabels:
      app: spanish-tutor-ui
  template:
    metadata:
      labels:
        app: spanish-tutor-ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python"]
          args: ["-m", "spanishtutor.src.main"]
          ports:
            - containerPort: 7860
          env:
            - name: API_URL
              value: "http://spanish-tutor-api:8000" 